name: GPT Translate per Commit

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "official/docs/**"
jobs:
  translate_root_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: get current changed files name
        id: current_changed_files
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep -E '^official/docs/[^/]+\.md$' | grep -v 'CHANGELOG\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        if: steps.current_changed_files.outputs.files != ''
        uses: FattySpring/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-4o-2024-08-06"
          max_tokens: 5000
          temperature: 0
          inputFiles: ${{ steps.current_changed_files.outputs.files }}
          outputFiles: "official/i18n/zh-TW/docusaurus-plugin-content-docs/current/*.md"
          languages: "繁体中文台湾"
          prompt: |
            你是一位专业的技术文档翻译专家， 请按照台湾的繁体中文习惯来翻译。
            请将以下 Markdown 内容翻译成 {targetLanguage}，并严格遵循以下规则：

            1. 保持原有格式：
               - 保持所有 Markdown 语法不变
               - 保留所有代码块和 HTML 标签
               - 保持原有的换行和空格
               - 保持所有链接和 URL 不变
               - 请不要返回 ```markdown 开头和 ``` 结尾的代码块

            2. 专业术语：
               - 保持所有技术术语为英文
               - 'Release'、'Preview' 等词保持英文
               - 保持所有版本号和技术规格不变
               - 将 '扩展' 翻译为 '擴充套件'
               - 将 '视频' 翻译为 '影片'
               - 将 '文件' 翻译为 '檔案'
               - 将 '设置' 翻译为 '設定'
               - 将 '进阶' 翻译为 '進階'
               - 将 '插件' 翻译为 '外掛'
          basePath: ${{ secrets.OPENAI_BASE_PATH }}

  translate_services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: get services changed files name
        id: services_changed_files
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep -E '^official/docs/services/.*\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        if: steps.services_changed_files.outputs.files != ''
        uses: FattySpring/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-4o-2024-08-06"
          max_tokens: 5000
          temperature: 0
          inputFiles: ${{ steps.services_changed_files.outputs.files }}
          outputFiles: "official/i18n/zh-TW/docusaurus-plugin-content-docs/current/services/*.md"
          languages: "繁体中文台湾"
          prompt: |
            你是一位专业的技术文档翻译专家， 请按照台湾的繁体中文习惯来翻译。
            请将以下 Markdown 内容翻译成 {targetLanguage}，并严格遵循以下规则：

            1. 保持原有格式：
               - 保持所有 Markdown 语法不变
               - 保留所有代码块和 HTML 标签
               - 保持原有的换行和空格
               - 保持所有链接和 URL 不变
               - 请不要返回 ```markdown 开头和 ``` 结尾的代码块

            2. 专业术语：
               - 保持所有技术术语为英文
               - 'Release'、'Preview' 等词保持英文
               - 保持所有版本号和技术规格不变
               - 将 '扩展' 翻译为 '擴充套件'
               - 将 '视频' 翻译为 '影片'
               - 将 '文件' 翻译为 '檔案'
               - 将 '设置' 翻译为 '設定'
               - 将 '进阶' 翻译为 '進階'
               - 将 '插件' 翻译为 '外掛'
          basePath: ${{ secrets.OPENAI_BASE_PATH }}

  translate_features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with two latest commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: get features changed files name
        id: features_changed_files
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep -E '^official/docs/features/[^/]+\.md$'  | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run GPT Translate
        if: steps.features_changed_files.outputs.files != ''
        uses: FattySpring/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-4o-2024-08-06"
          max_tokens: 5000
          temperature: 0
          inputFiles: ${{ steps.features_changed_files.outputs.files }}
          outputFiles: "official/i18n/zh-TW/docusaurus-plugin-content-docs/current/features/*.md"
          languages: "繁体中文台湾"
          prompt: |
            你是一位专业的技术文档翻译专家， 请按照台湾的繁体中文习惯来翻译。
            请将以下 Markdown 内容翻译成 {targetLanguage}，并严格遵循以下规则：

            1. 保持原有格式：
               - 保持所有 Markdown 语法不变
               - 保留所有代码块和 HTML 标签
               - 保持原有的换行和空格
               - 保持所有链接和 URL 不变
               - 请不要返回 ```markdown 开头和 ``` 结尾的代码块

            2. 专业术语：
               - 保持所有技术术语为英文
               - 'Release'、'Preview' 等词保持英文
               - 保持所有版本号和技术规格不变
               - 将 '扩展' 翻译为 '擴充套件'
               - 将 '视频' 翻译为 '影片'
               - 将 '文件' 翻译为 '檔案'
               - 将 '设置' 翻译为 '設定'
               - 将 '进阶' 翻译为 '進階'
               - 将 '插件' 翻译为 '外掛'
          basePath: ${{ secrets.OPENAI_BASE_PATH }}
